---
title: "ASO trial analysis"
author: "Lian Rui"
date: "2026-09-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Background

## Packages

```{r packages}
library(readxl) # import excel
library(readr) # read text with delim "|"
library(tidyverse)
library(lubridate)
library(ggraph)
```

## Getting data 1: MeSH setup

```{r MeSH setup}
mesh_labels <- read_csv("~/Documents/MeSH/mesh_labels.csv")

mesh_parent <- read_csv("~/Documents/MeSH/mesh_parent.csv")

mesh_tree <- read_csv("~/Documents/MeSH/mesh_tree.csv")

tree_names <- read_csv("~/Documents/MeSH/tree_names.csv")
```

## Getting data 2: AACT setup

```{r AACT import}
# studies
studies <- read_delim("/Volumes/My Passport/aact_Aug_2026_csv/studies.txt", 
                      delim = "|", escape_double = FALSE, trim_ws = TRUE)

# Select columns of studies
studies <- studies |>
  select(nct_id, 
         study_first_submitted_date, 
         start_date, 
         completion_date, 
         study_type, 
         brief_title, 
         official_title, 
         overall_status, 
         phase, 
         enrollment, 
         source, 
         source_class) |>
  filter(source_class == "INDUSTRY")


# MeSH condition
browse_conditions <- read_delim("/Volumes/My Passport/aact_Aug_2026_csv/browse_conditions.txt",
                                delim = "|", escape_double = FALSE, trim_ws = TRUE)

# Condistions
conditions <- read_delim("/Volumes/My Passport/aact_Aug_2026_csv/conditions.txt",
                                delim = "|", escape_double = FALSE, trim_ws = TRUE)

# MeSH intervention
browse_interventions <- read_delim("/Volumes/My Passport/aact_Aug_2026_csv/browse_interventions.txt",
                               delim = "|", escape_double = FALSE, trim_ws = TRUE)

# Interventions.txt
interventions <- read_delim("/Volumes/My Passport/aact_Aug_2026_csv/interventions.txt",
                               delim = "|", escape_double = FALSE, trim_ws = TRUE)

# intervention_other_names.txt
intervention_other_names <- read_delim("/Volumes/My Passport/aact_Aug_2026_csv/intervention_other_names.txt",
                               delim = "|", escape_double = FALSE, trim_ws = TRUE)

# Countries
# For the disease area analysis, country is not needed
countries <- read_delim("/Volumes/My Passport/aact_Aug_2026_csv/countries.txt", 
                         delim = "|", escape_double = FALSE, trim_ws = TRUE)

# design_groups
#design_groups <- read_delim("/Volumes/My Passport/aact_Aug_2026_csv/design_groups.txt", 
#                            delim = "|", escape_double = FALSE, trim_ws = TRUE)
## design_groups is not very useful for now. 

# designs outcomes
# The endpoint of each trial
# design_outcomes <- read_delim("/Volumes/My Passport/aact_Aug_2026_csv/design_outcomes.txt",
#                               delim = "|", escape_double = FALSE, trim_ws = TRUE)

# designs <- read_delim("/Volumes/My Passport/aact_Aug_2026_csv/designs.txt", 
#     delim = "|", escape_double = FALSE, trim_ws = TRUE)
# View(designs)

# facilities
#facilities <- read_delim("/Volumes/My Passport/aact_Aug_2026_csv/facilities.txt", 
#                         delim = "|", escape_double = FALSE, trim_ws = TRUE)
## Put facilities on hold

# sponsors
sponsors <- read_delim("/Volumes/My Passport/aact_Aug_2026_csv/sponsors.txt", 
                       delim = "|", escape_double = FALSE, trim_ws = TRUE)



```

## ASO analysis

### ASO nct_id

```{r aso nct_id}
# Import the nct_id on ADC
# This is from AACT PostgreSQL in dbeaver
# Fetched data pasted in excel
aso <- read_excel("~/Library/Mobile Documents/com~apple~CloudDocs/Project2026/OSA and siRNA/ASO and siRNA/aso nct_id sep.xlsx", col_names = FALSE)

# Remove the duplicated rows
# Why duplicated rows: 
# Same word is used to search multiple tables in AACT
# and same nct_id and drug name are returned
aso <- aso %>%
  distinct()

# Column names
colnames(aso) <- c("drug", "nct_id")

# Remove drug name = RNA, Antisense
#aso <- aso %>%
#  filter(!drug %in% "RNA, Antisense")

# Many minor difference on drug names
# drug name to lower case and distinct value again
aso <- aso %>%
  mutate(drug = trimws(drug)) %>%
  mutate(drug = tolower(drug)) %>%
  distinct()
```

### Trend: Number of trials each year in last five year

```{r}
trial_number_year <- studies |>
  select(nct_id, study_first_submitted_date) |>
  left_join(aso, by = join_by(nct_id)) |>
  drop_na() |>
  mutate(year = year(study_first_submitted_date)) 

dat <- trial_number_year |>
  group_by(year) |>
  summarise(n = n())

ggplot(dat) + 
  geom_col(aes(x = year, y = n))
```

### Trend: Duration of trials by year, phase

```{r}
trial_duration <- studies |>
  select(nct_id, start_date, completion_date, phase) |>
  mutate(year = year(start_date))|>
  filter(year >= 2020) |>
  left_join(aso, by = join_by(nct_id)) |>
  drop_na() |>
  mutate(
    time_interval = round(
      time_length(interval(start_date, completion_date), "months"),
      1
    )
  )
  
ggplot(trial_duration, aes(x = factor(year), y = time_interval)) + 
  geom_point() + 
  geom_boxplot(aes(x = factor(year))) + 
  facet_grid(phase~.)
```

### Trend: enrollment

```{r}
enrollment <- studies |>
  select(nct_id, study_first_submitted_date, phase, enrollment) |>
  mutate(year = year(study_first_submitted_date)) |>
  filter(year >= 2021) |>
  left_join(aso, by = join_by(nct_id)) |>
  filter(!is.na(phase))

ggplot(enrollment, aes(x = factor(year), y = enrollment)) +
  geom_point() + 
  geom_boxplot() + 
  facet_grid(phase~., scales = "free_y")
```

#### TODO Trend: enrollment by disease

### Trend: Number of trials by sponsor

```{r}
number_trial_sponsor <- studies |>
  select(nct_id, study_first_submitted_date, phase, source) |>
  mutate(year = year(study_first_submitted_date)) |>
  filter(year >= 2021) |>
  filter(!is.na(phase)) |>
  right_join(aso, by = join_by(nct_id)) |>
  drop_na() |>
  summarise(n = n(), .by = c(source, phase)) |>
  group_by(phase) |>
  slice_max(n, n = 10, with_ties = FALSE) |>
  arrange(phase, desc(n)) |>
  ungroup()

ggplot(number_trial_sponsor, aes(reorder(source, n, FUN = sum), n))  + 
  geom_col(aes(fill = phase)) + 
  coord_flip()
```

### Global MeSH analysis

```{r Join aso with aact}
# Filter the ASO studies from the master studies tables
# Create aso specific study table. 
aso_study <- studies %>%
  filter(nct_id %in% aso$nct_id)

# join aso_study with browse_condition
aso_study <- aso_study %>%
  left_join(browse_conditions, by = "nct_id")

# Join aso_study with countries
aso_study <- aso_study %>%
  left_join(countries, by = "nct_id")

# Join aso_study with facilities
#adc_study <- adc_study %>%
#  left_join(facilities, by = "nct_id")
## Put facilities on hold

# Join aso_study with sponsors
aso_study <- aso_study %>%
  left_join(sponsors, by = "nct_id")
```


```{r rename columns}
# Rename the aso_study
aso_study <- aso_study |>
  rename(country = name.x, 
         company = name.y)
```


```{r column selection}
# Select columns
aso_study <- aso_study %>%
  select(nct_id, study_first_submitted_date, start_date, 
         completion_date, study_type, brief_title, official_title, 
         overall_status, phase, enrollment, source, source_class, 
         downcase_mesh_term, mesh_type, country, company)


# There is a column source in study, which is the info of a study
# the source is contained in table sponsor, column company
# a single study may have many companies, e.g, 
# NCT02508090 has two companies: Santaris Pharma A/S and Hoffmann-La Roche
# As such, remove the column company, but the agency_type should be kept to
# Filter the Industry studies
aso_study <- aso_study |>
  select(!company)
```


```{r Industry study}
# The industry only
aso_study <- aso_study %>%
  filter(source_class %in% "INDUSTRY") |>
  distinct()
```


```{r Remove mesh-ancestor}
# Each study nct_id has many MeSH terms, 
# Most of them are mesh-ancestor
# i.e., the upper hierarchies of a special condition
# e.g., cystic fibrosis has ancestors like congenital, hereditary, and neonatal diseases and abnormalities, genetic diseases, inborn...
# As such, to remove the mesh-ancestor mesh type
# the more detailed hierarchy will be recreated using standalone mesh data
aso_study <- aso_study |>
  filter(mesh_type %in% "mesh-list") |>
  distinct()

# Join the drug name in table aso
aso_study <- aso_study |>
  left_join(aso, by = join_by(nct_id))
```


```{r network functions}
source("R/mesh_network_with_drug.R")

# ---------------------------------------------------------
# 1. Prepare trial data
# ---------------------------------------------------------

ta <- aso_study %>%
  filter(
    phase == "PHASE3",
    mesh_type == "mesh-list",
    source_class == "INDUSTRY"
  ) |>
  select(-country) |>
  distinct() |>
  mutate(
    year = lubridate::year(study_first_submitted_date)
  ) |>
  relocate(
    year,
    .after = study_first_submitted_date
  ) |>
  filter(year >= 2021) |>
  arrange(year)

# ---------------------------------------------------------
# 2. Count trials for each MeSH condition
# ---------------------------------------------------------

condition_trials <- ta |>
  distinct(
    nct_id,
    downcase_mesh_term
  ) |>
  count(
    downcase_mesh_term,
    name = "n_trials"
  ) 

# ---------------------------------------------------------
# 3. Get MeSH hierarchy
# ---------------------------------------------------------

aso_hierarchy_phase_3 <- get_hierarchy(
  unique(ta$downcase_mesh_term),
  tree_names
)

aso_hierarchy_phase_3 <- ta |>
  select(downcase_mesh_term, drug) |>
  left_join(
    aso_hierarchy_phase_3,
    by = c( "downcase_mesh_term" = "query_name")
  )

aso_hierarchy_phase_3 <- aso_hierarchy_phase_3 |>
  rename("query_name" = "downcase_mesh_term")

# ---------------------------------------------------------
# 4. Compress hierarchy
#    Cxx -> disease
#    + number of trials
# ---------------------------------------------------------

hierarchy_network <- compress_hierarchy(
  aso_hierarchy_phase_3,
  condition_trials
)

# ---------------------------------------------------------
# 5. Create network
# ---------------------------------------------------------

aso_network <- make_mesh_network(
  hierarchy_network
)

plot_mesh_network(aso_network)
```


## China study

```{r}
# China study
aso_china <- aso_study %>%
  filter(country %in% "China")

# Remove the column drug
# This represent the global
# Not all the drugs are used in China
aso_china <- aso_china |>
  select(!drug)

# Join browse intervention by nct_id in China
aso_china <- aso_china |>
  mutate(year = year(study_first_submitted_date)) |>
  relocate(year, .after = study_first_submitted_date) |>
  filter(year >= 2021) |>
  left_join(browse_interventions, by = join_by(nct_id)) |>
  select(
    -mesh_term, # keep downcase column only
    -id
  ) |>
  rename("disease" = "downcase_mesh_term.x",
         "drug" = "downcase_mesh_term.y") |>
  filter(mesh_type.x == "mesh-list", 
         mesh_type.y == "mesh-list") |>
  distinct() |>
  arrange(phase)

aso_china <- aso_china |>
  select(nct_id,brief_title, official_title,  drug, source, phase, enrollment, disease)


```


```{r}
aso_china <- aso_china |>
  select(nct_id, drug, source, phase, enrollment, disease) |>
  distinct()
```


```{r}
write_csv(aso_china, "aso_china.csv")
```
